name: Unzip File

on:
  push:
    branches:
      - main  # Kích hoạt khi có thay đổi trên nhánh chính

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip the file
        run: |
          unzip simply-static-1-1737800006.zip -d extracted_contents

      - name: Commit and Push Unzipped Contents
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git add extracted_contents/
          git commit -m "Add unzipped contents"
          git push
