name: Unzip File

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify File Exists
        run: ls -l simply-static-1-1737800006.zip

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip the file
        run: unzip simply-static-1-1737800006.zip -d extracted_contents

      - name: Commit and Push Unzipped Contents
        run: |
          git config user.name "juno2987"
          git config user.email "vuduyan.1996@gmail.com"
          git add extracted_contents/
          git commit -m "Add unzipped contents"
          git push
